### ISSUE TITLE
Wrong redirection + name

### ISSUE THREAD

**Issue by Wabri** [Schroedinger-Hat/schroedinger-hat-website#134]
### Reproduction

- open the website https://schroedinger-hat.org/
- click to the github logo on the top right
- get github 404 because the right url is https://github.com/Schroedinger-Hat

### Describe the bug

There are a lot of wrong redirection to old naming schrodinger-hat: https://github.com/search?q=repo%3ASchroedinger-Hat%2Fschrodinger-hat-website%20schrodinger&type=code

### Additional context

I can solve it

**Comment by Readpato** [comment]
Hmm, I look out for more redirection issues inside the app. 

Where did you get the last link from?

**Comment by Wabri** [comment]
It is the github search for schrodinger in this repository

**Comment by Readpato** [comment]
I have partially addressed this issue with the PR above.

Whenever our social media platforms are ready, we could also replace the old name refuses that still exist in the app.

**Comment by Readpato** [comment]
I think we can close this issue, what do you think @Wabri?

**Comment by Wabri** [comment]
Yes 👍
