### ISSUE TITLE
Update repository name

### ISSUE THREAD

**Issue by Readpato** [Schroedinger-Hat/schroedinger-hat-website#136]
### Describe the feature

Update the name of the repository to properly address new official name of the community (Schrodinger => Schroedinger)

Name of the repository could change to: schroedinger-hat-website or sh-website (for a shorter version).

What do you think @Wabri @TheJoin95?

What do you think?

(Partially addresses #134)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [code of conduct](https://www.schroedinger-hat.org/code-of-conduct).
- [X] Check existing [issues](https://github.com/Schrodinger-Hat/schrodinger-hat-website/issues).

**Comment by Wabri** [comment]
It is a must for me, so yes!

I'm more in the side of using the complete name: schroedinger-hat-web/website, but do what you think is better to do!

**Comment by Readpato** [comment]
The title `schroedigner-hat-website` is also good for me, let's see what @TheJoin95 has to say about the naming and then I will proceed with updating it

**Comment by TheJoin95** [comment]
I'm ok with that, let's go!

**Comment by Wabri** [comment]
Updated!

**Comment by Wabri** [comment]
I leave the close action to @Readpato if he wants to leave it open till the #135 is merged

**Comment by Readpato** [comment]
I'll close it now and update #135, thanks @Wabri and @TheJoin95 for your contributions :)
